version: "3"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: MINIO_SECRET_KEY
    command: server --compat /data
  db:
    image: postgres:10.1-alpine
    container_name: "s3-and-db-sample-db"
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: s3-and-db-sample-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: yt8492/s3-and-db-sample:latest
    container_name: "s3-and-db-sample"
    ports:
      - "8492:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/s3-and-db-sample-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      AWS_ACCESS_KEY_ID: MINIO_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: MINIO_SECRET_KEY
      S3_URL: http://minio:9000
    depends_on:
      - db
      - minio
volumes:
  db-data:
    driver: local